# Generated by Django 5.1.4 on 2024-12-16 09:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Место выполнения привычки",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Выберете время когда необходимо выполнять привычку",
                        null=True,
                        verbose_name="Время старта",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="Укажите действие привычки",
                        max_length=300,
                        null=True,
                        verbose_name="Действие привычки",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка является приятной",
                        verbose_name="Признак приятной привычки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("every day", "каждый день"),
                            ("once a week", "раз в неделю"),
                            ("twice a week", "дважды в неделю"),
                            ("three times a week", "трижды в неделю"),
                            ("four times a week", "четыре раза в неделю"),
                            ("five times a week", "пять раз в неделю"),
                            ("six times a week", "шесть раз в неделю"),
                        ],
                        default="every day",
                        help_text="Укажите переодичность выполнения привычки",
                        max_length=25,
                        verbose_name="Переодичность выполнения привычки",
                    ),
                ),
                (
                    "remuneration",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Вознаграждение после выполнения привычки",
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="Время выполнения привычки",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Опубликовать для общего доступа",
                        verbose_name="Публикация в общем доступе",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите автора привычки",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users_habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор привычки",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_habits",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
        ),
    ]
