# Generated by Django 5.1.4 on 2024-12-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="habit",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Привычка"
            ),
        ),
    ]
