# Generated by Django 5.1.4 on 2024-12-18 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habits", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите автора привычки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users_habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор привычки",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_habits",
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
    ]
