# Generated by Django 5.1.4 on 2024-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.PositiveIntegerField(help_text='Укажите переодичность выполнения привычки', max_length=1, verbose_name='Периодичность выполнения привычки'),
        ),
    ]
