# Generated by Django 5.1.4 on 2024-12-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveIntegerField(
                help_text="Укажите переодичность выполнения привычки",
                verbose_name="Периодичность выполнения привычки в неделю",
            ),
        ),
    ]
